version: '3.9'
services:
  backend:
    build: .
    command: uvicorn app_quote_api:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - '8000:8000'

  frontend:
    build: .
    command: streamlit run gui/app.py --server.port 8501 --server.headless true
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - '8501:8501'
    depends_on:
      - backend
